manifest-version: 0
tags:
  abc: {}
  def: {}
  ghi:
    name: GHI Tag
  jkl:
    description: This is a tag with id 'jkl'
  mno:
    name: MNO Tag
    description: This is a tag with id 'mno'
tasks:
  - status: active
    summary: first task
  - status: active
    summary: task with a sub
    sub:
      - status: active
        summary: first sub task
  - status: active
    summary: task with 2 subs
    sub:
      - status: completed
        summary: completed sub task
      - status: active
        summary: active sub task
