manifest-version: 0
tags:
  abc: {}
  def: {}
  ghi:
    name: GHI Tag
  jkl:
    description: This is a tag with id 'jkl'
  mno:
    name: MNO Tag
    description: This is a tag with id 'mno'
tasks:
  - status: active
    summary: first task
    tags:
      - abc
      - def
      - ghi
  - status: active
    summary: task with a sub
    tags:
      - abc
    sub:
      - status: active
        summary: first sub task
        tags:
          - def
  - status: active
    summary: task with 2 subs
    sub:
      - status: completed
        summary: completed sub task
      - status: active
        summary: active sub task
  - status: active
    summary: deep sub task levels
    sub:
      - status: active
        summary: deep sub task levels 1
        tags:
          - abc
        sub:
          - status: completed
            summary: deep sub task levels 1a
          - status: active
            summary: deep sub task levels 1b
      - status: completed
        summary: deep sub task levels 2
        tags:
          - def
        sub:
          - status: active
            summary: deep sub task levels 2a
            tags:
              - ghi
